version: '3.8'

services:
  web-app:
    build: .
    container_name: ibb-scraper-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app           # Mevcut klasÃ¶rÃ¼ konteynerdeki /app'e baÄŸla
      - /app/node_modules # Konteynerin kendi kÃ¼tÃ¼phanelerini koru
      - /app/.next
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    # ğŸ‘‡ GeliÅŸtirme aÅŸamasÄ±nda 'npm start' yerine 'npm run dev' kullanmalÄ±sÄ±n
    command: npm run dev 
    restart: always